laika.title = "Getting Started"

laika.navigationOrder = [
  01-for-the-impatient.md
  02-what-is-scalafx.md
  03-installation-and-setup.md
  04-your-first-scalafx-app.md
  05-anatomy-of-a-scalafx-application.md
  06-further-resources.md
]